// examples/components/some-react-component.js
/**
 * Here you create a React component like always...
 * We are ONLY defining the component.
 *
 * some-react-component-ecbundle.js
 */
import React, { Component } from 'react';

class MyCarousel extends Component {
  constructor(props) {
    super(props)

    this.state = {
      counter: 0
    };
  }
    render() {
		try {
			var scriptUrl = document.currentScript.src;
		} catch (err) {
			var scriptUrl = false
		}
      return (
        <div style={ {border: "3px solid red", padding: '10px'} }>
          <h1 style={ { margin: 0 } }>Example React component</h1>
          { this.props.param1 && <div>Value of param1: { this.props.param1 }</div> }
          { this.props.param2 && <div>Value of param2: { this.props.param2 }</div> }
		  <button onClick={this.incrementCounter.bind(this)}>Increment counter</button>
		  <div>Counter value: { this.state.counter } </div>

		  { !scriptUrl ? '' : (
			<div>
				<p>Embed me:</p>
				<pre style={ { background: '#ddd' , padding: '10px' } }>
					&lt;some-react-component param1="p1..." param2="p2..."&gt;&lt;/some-react-component&gt;<br/>
					&lt;script src="{scriptUrl}"&gt;&lt;/script&gt;
				</pre>
			</div>
		  )}
        </div>
      )
    }
    incrementCounter(event) {
      var myEvent = new CustomEvent('increment-counter', { bubbles: true });

      event.target.dispatchEvent(myEvent);

      this.setState(state => {
        return {
          counter: state.counter + 1
        }
      })
    }
  }
export default MyCarousel;

// examples/components/some-vue-component.vue
<template>
    <div style="border:3px solid green;padding:10px;">
        <h1 style="margin:0;">Example Vue component</h1>
        <div v-if="param1">Value of param1: {{param1}}</div>
        <div v-if="param2">Value of param2: {{param2}}</div>
        <button @click="incrementCounter()">Increment counter</button>

		<div v-if="scriptUrl" class="embed-me">
			<p>Embed me:</p>
			<pre>
				&lt;some-vue-component param1="p1.." param2="p2..."&gt;&lt;/some-vue-component&gt;
				&lt;script src="{{scriptUrl}}"&gt;&lt;/script&gt;
			</pre>
		</div>
    </div>
</template>

<script>
export default {
    props: ['param1', 'param2'],
    data() {
        return {
			counter: 0,
			scriptUrl: false
        }
	},
	mounted() {
		try {
			this.scriptUrl = document.currentScript.src;
		} catch (err) {

		}
	},
    methods: {
        incrementCounter() {
            this.counter++;

            var myEvent = new CustomEvent('increment-counter', {bubbles: true});
            this.$el.dispatchEvent(myEvent);
        }
    }
}
</script>

<style>
.embed-me pre {
	padding: 10px;
	background: #ddd;
	white-space: pre-line;
}
</style>
