// examples/components/some-svelte-component.svelte
<script>
let counter = 0;
export let param1;
export let param2;

let scriptUrl;
try {
	scriptUrl = document.currentScript.src;
} catch (ignore) {}

let container

function incrementCounter(event) {
	counter++;

	var myEvent = new CustomEvent('increment-counter', {bubbles: true});
	container.parentNode.dispatchEvent(myEvent);
}

</script>

<style>
.container {
	border: 3px solid orange;
	padding: 1rem;
}

h1 {
	padding: 0;
	margin: 0;
}
</style>

<div class="container" bind:this={container}>
	<h1>Svelte component</h1>

	{#if param1}
		<div>Value of param1: {param1}</div>
	{/if}

	{#if param2}
		<div>Value of param2: {param2}</div>
	{/if}

	<button on:click={ incrementCounter }>Increment counter</button>

	<p>
		Counter value: {counter}
	</p>

	{#if scriptUrl}
	<pre style="background: #ddd; padding: 10px;white-space:pre-line;">
		&lt;some-svelte-component param1="p1..." param2="p2..."&gt;&lt;/some-svelte-component&gt;<br/>
		&lt;script src="{scriptUrl}"&gt;&lt;/script&gt;
	</pre>
	{/if}
</div>

// examples/components/some-vue-component.vue
<template>
    <div style="border:3px solid green;padding:10px;">
        <h1 style="margin:0;">Example Vue component</h1>
        <div v-if="param1">Value of param1: {{param1}}</div>
        <div v-if="param2">Value of param2: {{param2}}</div>
        <button @click="incrementCounter()">Increment counter</button>

		<div v-if="scriptUrl" class="embed-me">
			<p>Embed me:</p>
			<pre>
				&lt;some-vue-component param1="p1.." param2="p2..."&gt;&lt;/some-vue-component&gt;
				&lt;script src="{{scriptUrl}}"&gt;&lt;/script&gt;
			</pre>
		</div>
    </div>
</template>

<script>
export default {
    props: ['param1', 'param2'],
    data() {
        return {
			counter: 0,
			scriptUrl: false
        }
	},
	mounted() {
		try {
			this.scriptUrl = document.currentScript.src;
		} catch (err) {

		}
	},
    methods: {
        incrementCounter() {
            this.counter++;

            var myEvent = new CustomEvent('increment-counter', {bubbles: true});
            this.$el.dispatchEvent(myEvent);
        }
    }
}
</script>

<style>
.embed-me pre {
	padding: 10px;
	background: #ddd;
	white-space: pre-line;
}
</style>
